# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ujikoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem
from datetime import datetime

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 790)
        self.pushButtonLoad = QtWidgets.QPushButton(Form)
        self.pushButtonLoad.setGeometry(QtCore.QRect(40, 410, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pushButtonLoad.setFont(font)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.pushButtonCari = QtWidgets.QPushButton(Form)
        self.pushButtonCari.setGeometry(QtCore.QRect(40, 660, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pushButtonCari.setFont(font)
        self.pushButtonCari.setObjectName("pushButtonCari")
        self.lineEditCari = QtWidgets.QLineEdit(Form)
        self.lineEditCari.setGeometry(QtCore.QRect(180, 660, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEditCari.setFont(font)
        self.lineEditCari.setObjectName("lineEditCari")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 30, 351, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditnpm = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEditnpm.setFont(font)
        self.lineEditnpm.setObjectName("lineEditnpm")
        self.verticalLayout.addWidget(self.lineEditnpm)
        self.lineEditnama = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEditnama.setFont(font)
        self.lineEditnama.setObjectName("lineEditnama")
        self.verticalLayout.addWidget(self.lineEditnama)
        self.lineEditkelas = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEditkelas.setFont(font)
        self.lineEditkelas.setObjectName("lineEditkelas")
        self.verticalLayout.addWidget(self.lineEditkelas)
        self.lineEditjurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEditjurusan.setFont(font)
        self.lineEditjurusan.setObjectName("lineEditjurusan")
        self.verticalLayout.addWidget(self.lineEditjurusan)
        self.lineEdittgllahir = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.lineEdittgllahir.setFont(font)
        self.lineEdittgllahir.setObjectName("lineEdittgllahir")
        self.verticalLayout.addWidget(self.lineEdittgllahir)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 111, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelnpm = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelnpm.setFont(font)
        self.labelnpm.setObjectName("labelnpm")
        self.verticalLayout_2.addWidget(self.labelnpm)
        self.labelnama = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelnama.setFont(font)
        self.labelnama.setObjectName("labelnama")
        self.verticalLayout_2.addWidget(self.labelnama)
        self.labelkelas = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labelkelas.setFont(font)
        self.labelkelas.setObjectName("labelkelas")
        self.verticalLayout_2.addWidget(self.labelkelas)
        self.labeljurusan = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeljurusan.setFont(font)
        self.labeljurusan.setObjectName("labeljurusan")
        self.verticalLayout_2.addWidget(self.labeljurusan)
        self.labeltgllahir = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.labeltgllahir.setFont(font)
        self.labeltgllahir.setObjectName("labeltgllahir")
        self.verticalLayout_2.addWidget(self.labeltgllahir)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 330, 391, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonUbah = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pushButtonUbah.setFont(font)
        self.pushButtonUbah.setObjectName("pushButtonUbah")
        self.horizontalLayout.addWidget(self.pushButtonUbah)
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pushButtonInsert.setFont(font)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.pushButtonHapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.pushButtonHapus.setFont(font)
        self.pushButtonHapus.setObjectName("pushButtonHapus")
        self.horizontalLayout.addWidget(self.pushButtonHapus)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 460, 421, 181))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.pushButtonInsert.clicked.connect(self.simpandata)
        self.pushButtonLoad.clicked.connect(self.loadmahasiswa)
        self.pushButtonUbah.clicked.connect(self.ubahmahasiswa)
        self.pushButtonHapus.clicked.connect(self.hapusmahasiswa)
        self.pushButtonCari.clicked.connect(self.carimahasiswa)
        self.tableWidget.cellClicked.connect(self.getById)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def simpandata(self):
        npm = self.lineEditnpm.text()
        nama = self.lineEditnama.text()
        kelas = self.lineEditkelas.text()
        jurusan = self.lineEditjurusan.text()
        tgllahir = self.lineEdittgllahir.text()

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="dbkampus"
        )

        cursor = mydb.cursor()
        sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir) VALUES (%s, %s, %s, %s, %s)"
        val = (npm, nama, kelas, jurusan, tgllahir)
        cursor.execute(sql, val)
        mydb.commit()
        self.loadmahasiswa()
        self.lineEditnpm.clear()
        self.lineEditnama.clear()
        self.lineEditkelas.clear()
        self.lineEditjurusan.clear()
        self.lineEdittgllahir.clear()

    def loadmahasiswa(self):
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="dbkampus"
        )

        mycursor = mydb.cursor()
        mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
        result = mycursor.fetchall()
        self.tableWidget.setRowCount(0)
        if result:
            self.tableWidget.setColumnCount(len(result[0]))
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

    def getById(self, row):
        npmItem = self.tableWidget.item(row, 0)
        nameItem = self.tableWidget.item(row, 1)
        kelasItem = self.tableWidget.item(row, 2)
        jurusanItem = self.tableWidget.item(row, 3)
        tgllahirItem = self.tableWidget.item(row, 4)

        if npmItem:
            npm = npmItem.text()
            nama = nameItem.text()
            kelas = kelasItem.text()
            jurusan = jurusanItem.text()
            tglLahir = tgllahirItem.text()
            self.lineEditnpm.setText(npm)
            self.lineEditnama.setText(nama)
            self.lineEditkelas.setText(kelas)
            self.lineEditjurusan.setText(jurusan)
            self.lineEdittgllahir.setText(tglLahir)

    def ubahmahasiswa(self):
        npm = self.lineEditnpm.text()
        nama = self.lineEditnama.text()
        kelas = self.lineEditkelas.text()
        jurusan = self.lineEditjurusan.text()
        tgllahir = self.lineEdittgllahir.text()

        if not npm or not nama or not kelas or not jurusan or not tgllahir:
            return 

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="dbkampus"
        )
        cursor = mydb.cursor()
        sql = "UPDATE mahasiswa SET nama = %s, kelas = %s, jurusan = %s, tanggal_lahir = %s WHERE npm = %s"
        val = (nama, kelas, jurusan, tgllahir, npm)
        cursor.execute(sql, val)
        mydb.commit()
        self.loadmahasiswa()

    def hapusmahasiswa(self):
        npm = self.lineEditnpm.text().strip()
        if not npm:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "NPM tidak boleh kosong!"
            )
            return

        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="dbkampus"
            )
            cursor = mydb.cursor()

            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,)
            cursor.execute(sql, val)
            mydb.commit()

            if cursor.rowcount > 0:
                QtWidgets.QMessageBox.information(
                    None, "Informasi", f"Data dengan NPM {npm} berhasil dihapus!"
                )
            else:
                QtWidgets.QMessageBox.warning(
                    None, "Peringatan", f"Data dengan NPM {npm} tidak ditemukan!"
                )

            self.loadmahasiswa()
            self.lineEditnpm.clear()
            self.lineEditnama.clear()
            self.lineEditkelas.clear()
            self.lineEditjurusan.clear()
            self.lineEdittgllahir.clear()
        except mc.Error as e:
            QtWidgets.QMessageBox.critical(
                None, "Kesalahan", f"Terjadi kesalahan saat menghapus data: {str(e)}"
            )
        finally:
            if mydb.is_connected():
                cursor.close()
                mydb.close()

    def carimahasiswa(self):
        keyword = self.lineEditCari.text().strip() 
        if not keyword:
            return  

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="dbkampus"
        )

        cursor = mydb.cursor()

        search_pattern = f"%{keyword}%"
        try:
            parsed_date = datetime.strptime(keyword, "%d-%m-%Y").strftime("%Y-%m-%d")
            search_pattern_date = f"%{parsed_date}%"
        except ValueError:
            search_pattern_date = search_pattern

        sql = """
        SELECT * FROM mahasiswa 
        WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s 
        OR jurusan LIKE %s OR tanggal_lahir LIKE %s
        """
        val = (search_pattern, search_pattern, search_pattern, search_pattern, search_pattern_date)
        cursor.execute(sql, val)
        result = cursor.fetchall()

        self.tableWidget.setRowCount(0)
        if result:
            self.tableWidget.setColumnCount(len(result[0]))
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        else:
            self.tableWidget.setColumnCount(0)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonLoad.setText(_translate("Form", "Load Data"))
        self.pushButtonCari.setText(_translate("Form", "Cari Data"))
        self.labelnpm.setText(_translate("Form", "NPM"))
        self.labelnama.setText(_translate("Form", "Nama"))
        self.labelkelas.setText(_translate("Form", "Kelas"))
        self.labeljurusan.setText(_translate("Form", "Jurusan"))
        self.labeltgllahir.setText(_translate("Form", "Tanggal Lahir"))
        self.pushButtonUbah.setText(_translate("Form", "Ubah Data"))
        self.pushButtonInsert.setText(_translate("Form", "Simpan Data"))
        self.pushButtonHapus.setText(_translate("Form", "Hapus Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "npm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "tanggal_lahir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
